# Generated by Django 3.1.1 on 2020-09-30 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('togetherapp', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('canvasDataURL', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('colors', models.CharField(blank=True, choices=[('#eb0000', 'Red'), ('#ff94f8', 'Pink'), ('#369aff', 'Blue'), ('#1dcf0c', 'Green')], max_length=7)),
                ('priority', models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')])),
                ('due_date', models.DateTimeField(blank=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='togetherapp.list')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='togetherapp.room'),
        ),
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='togetherapp.room'),
        ),
    ]
