# Generated by Django 3.1.1 on 2020-09-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togetherapp', '0004_auto_20200930_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='canvasDataURL',
            field=models.TextField(default=' '),
        ),
    ]
