# Generated by Django 3.1.1 on 2020-09-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togetherapp', '0007_auto_20200930_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='colors',
            field=models.CharField(blank=True, choices=[('#eb0000', 'Red'), ('#ff94f8', 'Pink'), ('#369aff', 'Blue'), ('#1dcf0c', 'Green'), ('#000000', 'Black')], max_length=7),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Medium'), (3, 'Low'), (0, 'None')], default=0),
        ),
    ]
