# Generated by Django 3.1.1 on 2020-09-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('togetherapp', '0008_auto_20200930_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
